# Generated by Django 2.2.5 on 2019-10-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('cons', models.TextField()),
                ('discussion', models.TextField()),
            ],
        ),
    ]
